####################################################################################################################################################################
#
# Configuration file for TestParser.ps1
#
# Filename: "config.conf"
# 
# File Context:
# Lines that begin with '#' are ignored.
# Required lines:
#   - etcUrl: The base URL for the ETC service.
#   - Format: The data format used for communication.
#   - TokenUrl: URL to request the authentication token.
#   - WsUrl: URL for the web service endpoint.
#   - documentation: URL for the API documentation.
#
# Case-Sensitivity:
# Variable names and all tags are case-insensitive. Values are case-sensitive where applicable.
#
# Format for basic value assignment lines:
#   <variable_name> = <string>
#     (spacing before or after '=' is ignored)
#   where:
#     <variable_name> can be any single, case-insensitive word of
#       alphanumeric characters with underscores,
#       but cannot start with a digit.
#     <string> can be any set of characters up to the end of the line.
#       The string does not require quotes.
#       Any quotes will be retained as either single or double.
#       Any trailing whitespace will be added to <string> if there are NO quotes.
#
####################################################################################################################################################################

# Base URL for the ETC service
etcUrl = www.etc-iwtc-cs-cso.com

# Format used for communication
Format = json

# URL to request the authentication token
TokenUrl = https://www.etc-iwtc-cs-cso.com/login/token.php

# URL for the web service endpoint
WsUrl = https://www.etc-iwtc-cs-cso.com/webservice/rest/server.php

# URL for the API documentation
documentation = https://sandbox.moodledemo.net/admin/webservice/documentation.php
